name: Deploy to S3

on:
  push:
    branches:
      - main
    paths:
      - "frontend/index.html"
      - "frontend/styles.css"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Deploy to S3
        run: aws s3 sync . s3://giokeels.com --delete --exclude ".git/*" --exclude ".github/*" --exclude "backend/*" --exclude "journal.md" --exclude "README.md"

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id E2KEHCNBU58GU4 --paths "/*"
